# Generated by Django 5.1.5 on 2025-03-13 11:41

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
